# Generated by Django 6.0.3 on 2026-03-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_courses_student_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='weeks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
