# Generated by Django 6.0.3 on 2026-03-24 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_student_course_remove_student_weeks_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Bridgeon',
        ),
    ]
